server:
    port: 8083
    contextPath: /client

security:
    basic:
        enabled: false

config:
    oauth2:
        clientID: confidential
        clientSecret: secret
        accessTokenUri: http://192.168.0.137:8081/oauth/token
        userAuthorizationUri: http://192.168.0.137:8081/oauth/authorize
        resourceURI: http://192.168.0.137:8082/api/